#########################################################################################
#
#  Note that import order here is important,
#  so rearranging import lists is *not* recommended.
#
#########################################################################################

- name: Configure machine for development work
  hosts: 127.0.0.1
  connection: local

##### Operating system packages and configuration

- import_playbook: core.yaml

##### Developer tools

# Visual Studio Code
- import_playbook: vscode/core.yaml

# Docker
- import_playbook: docker/core.yaml

